Fix response schema for event stream
GREsau/okapi pull request #87
Opened 2022-05-09 09:52 UTC by codercengiz

Fix #86

2022-05-09 16:09 UTC, svenstaro requested changes

2022-05-09 16:09 UTC, svenstaro commented on rocket-okapi/src/gen.rs
> +#[allow(dead_code)]
Should we really allow this here? Why?

2022-05-10 07:59 UTC, codercengiz commented on rocket-okapi/src/gen.rs
> +#[allow(dead_code)]
I understand your concern, so I used _ instead of ``#[allow(dead_code)]

2022-05-20 04:10 UTC, svenstaro commented
@GREsau could you take a look at this please?

2022-05-26 11:02 UTC, Nukesor commented on rocket-okapi/src/gen.rs
> -    settings: OpenApiSettings,
I assume this `_` has been a mistake? It doesn't seem relevant for this MR.

2022-05-26 11:03 UTC, Nukesor commented on rocket-okapi/src/gen.rs
> +    _settings: OpenApiSettings,
I assume this _ has been a mistake? It doesn't seem relevant for this MR.

2022-06-05 16:49 UTC, svenstaro commented
@GREsau would be great to get this fix in before the next release now that master is compatible to current Rocket. :)

2022-06-05 17:22 UTC, ralpha commented on rocket-okapi/src/gen.rs
> +    _settings: OpenApiSettings,
Looks like this was just added to suppress an warning during compiling.

2022-06-05 17:27 UTC, ralpha commented
Thanks for the PR, this is partially merged in 7acd774f5307a02396bfa4018d208bbb75e7a652.
Other changes are not needed anymore.
This should be fixed in the next release.

2022-06-05 17:27 UTC, closed without merging